name: Add data
on:
  pull_request_target:
    types: [opened]
    branches:
      - new_pipeline_v4
  
jobs:
    copy_fork_pr:
        uses: MagnusSletten/Databank/.github/workflows/AddBranchPullRequest.yml@new_pipeline_v4
        with:
          working_branch_name: ${{ github.event.pull_request.head.ref }}
          target_branch_name: new_pipeline_v4
          pr_number: ${{ github.event.pull_request.number }}
        secrets: inherit 
  
    AddExperimentData:
      needs: copy_fork_pr
      uses: MagnusSletten/Databank/.github/workflows/AddExperimentData.yml@new_pipeline_v4
      with:
        working_branch_name: pr-${{ github.event.pull_request.number }}-from-fork
        target_branch_name: new_pipeline_v4
      secrets: inherit 
        
    AddSimulationData:
      needs: [AddExperimentData,copy_fork_pr]  # Ensure Add_Sim_Data waits for Add_Experiment_Data to finish
      uses: MagnusSletten/Databank/.github/workflows/AddSimulationData.yml@new_pipeline_v4
      with:
        working_branch_name: pr-${{ github.event.pull_request.number }}-from-fork
        target_branch_name: new_pipeline_v4
      secrets: inherit 
       