name: Handle Fork PRs

on:
  pull_request_target:
    branches:
      - new_pipeline_v3
    paths:
      - 'Scripts/BuildDatabank/info_files/**'

jobs:
  copy_fork_pr:
    if: github.repository == 'MagnusSletten/Databank' && github.event.pull_request.head.repo.full_name != 'MagnusSletten/Databank'
    runs-on: nrec-large
    steps:
        #The chechkout -b step here makes a new branch which starts from the most recent fetch.
      - name: Fetch and checkout forked branch
        run: |
          git fetch https://github.com/${{ github.event.pull_request.head.repo.full_name }} ${{ github.event.pull_request.head.ref }}
          git checkout -b pr-${{ github.event.pull_request.number }}-from-fork FETCH_HEAD  

 
      - name: Push the new branch
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} pr-${{ github.event.pull_request.number }}-from-fork:pr-${{ github.event.pull_request.number }}-from-fork

      - name: Fetch new branch
        run: |
           git fetch origin pr-${{ github.event.pull_request.number }}-from-fork
     
    
      - name: Authenticate gh
        run: |
          echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

 
      - name: Create pull request
        run: |
          gh pr create --head pr-${{ github.event.pull_request.number }}-from-fork --base new_pipeline_v3 --title "${{Github.actor}}'s New Simulation Data" --body "This PR brings in new simulation data from ${{Github.actor}}"
      
      
      - name: Pull Docker image
        run: |
            sudo docker pull nmrlipids/project:addsim_fork1.0

      - name: Run the Docker container with environment variables
        run: |
          sudo docker run --rm \
          --env REPO_URL=https://github.com/${{ github.repository }}.git \
          --env BRANCH_NAME=pr-${{ github.event.pull_request.number }}-from-fork \
          --env GH_TOKEN=${{ secrets.GH_TOKEN }} \
          --env TARGET_BRANCH=new_pipeline_v3 \
          nmrlipids/project:addsim_fork1.0