name: Add new data
#s
on:
  pull_request_target:
    branches:
      - new_pipeline_v2
    paths:
      - 'Scripts/BuildDatabank/info_files/**'

  workflow_dispatch:

  push:
    branches:
      - new_pipeline_v2

jobs:
  build:
    runs-on: nrec-large  
    if: github.repository == 'MagnusSletten/Databank' && github.event.pull_request.head.repo.full_name == 'MagnusSletten/Databank' && startsWith(github.event.pull_request.head.ref, 'pr')
    steps:

    - name: Get current branch name
      id: vars
      run: |
        branchName=${github.event.pull_request.head.ref}
        echo "BRANCH_NAME=$branchName" >> $GITHUB_ENV

    - name: Pull Docker image
      run: |
          sudo docker pull nmrlipids/project:addsim1.3

    - name: Run the Docker container with environment variables
      run: |
          sudo docker run --rm \
          --env REPO_URL=${{ github.event.repository.clone_url }} \
          --env BRANCH_NAME=${{ env.BRANCH_NAME }} \
          --env GH_TOKEN=${{ secrets.GH_TOKEN }} \
          nmrlipids/project:addsim1.3