name: Add new data
#s
on:
  pull_request_target:
    branches:
      - new_pipeline_v2
    paths:
      - 'Scripts/BuildDatabank/info_files/**'

  workflow_dispatch:

  push:
    branches:
      - new_pipeline_v2

jobs:
  build:
    runs-on: nrec-large  
    if: github.repository == 'MagnusSletten/Databank' && github.event.pull_request.head.repo.full_name != 'MagnusSletten/Databank'
    steps:
    - name: Check if PR is from the same repository
      id: check_pr_source
      run: |
        if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]]; then
          echo "This pull request is from a forked repository. Skipping build."
          exit 0
        else
          echo "This pull request is from the same repository."
        fi

    - name: Get current branch name
      id: vars
      run: |
        branchName=${GITHUB_REF#refs/heads/}
        echo "BRANCH_NAME=$branchName" >> $GITHUB_ENV

    - name: Pull Docker image
      run: |
          sudo docker pull nmrlipids/project:addsim1.3

    - name: Run the Docker container with environment variables
      run: |
          sudo docker run --rm \
          --env REPO_URL=${{ github.event.repository.clone_url }} \
          --env BRANCH_NAME=${{ env.BRANCH_NAME }} \
          --env GH_TOKEN=${{ secrets.GH_TOKEN }} \
          nmrlipids/project:addsim1.3